image: deployer:latest
services:
- docker:dind
before_script:
- docker version
- env
- sh /app/active.sh
stages:
- build
- release-uat
#- release-canary
- release

variables:
  BUILD_IMAGE: gcr.io/$GCP_PROJECT/$CI_PROJECT_NAME:$CI_COMMIT_SHA
  TAG_IMAGE: gcr.io/$GCP_PROJECT/$CI_PROJECT_NAME:$CI_COMMIT_TAG
  RELEASE_IMAGE: gcr.io/$GCP_PROJECT/$CI_PROJECT_NAME:latest

build:
  stage: build
  variables:
    NODE_ENV: 'uat'
  script:
  - docker build -t $BUILD_IMAGE .
  - docker  push  $BUILD_IMAGE
  only:
  - master
  tags:
  - docker-builder

release-uat:
  stage: release-uat
  script:
  - cd k8s
  - sed -i "s/latest/"$CI_COMMIT_SHA"/g" uat-{{name}}.yml
  - cat uat-{{name}}.yml
  - kubectl apply -f uat-{{name}}.yml
  only:
  - master
  tags:
  - docker-builder

#release-canary:
#  stage: release-canary
#  script:
#  - sed -i "s/latest/"$CI_COMMIT_SHA"/g" canary-{{name}}.yml
#  - cat canary-{{name}}.yml
#  - kubectl apply -f canary-{{name}}.yml
#  only:
#  - master
#  tags:
#  - docker-builder
#
#
release:
  stage: release
  script:
  - cd k8s
  - docker tag $BUILD_IMAGE $TAG_IMAGE
  - docker tag $BUILD_IMAGE $RELEASE_IMAGE
  - docker push $TAG_IMAGE
  - docker push $RELEASE_IMAGE
  - sed -i "s/latest/"$CI_COMMIT_TAG"/g" production-{{name}}.yml
  - cat production-{{name}}.yml
  - kubectl apply -f production-{{name}}.yml
  only:
  - /^release-.*$/
  tags:
  - docker-builder

